name: 'Check merges'
description: 'Check if any merges occurred in the last 24 hours'
inputs:
  TOKEN:
    description: 'Github Token'
    required: true
  REPO_NAME:
    description: 'Repository name'
    required: true
  ORG_NAME:
    description: 'Organization name'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Check if there were any merge events in the last 24 hours
      id: check_merges
      env:
        TOKEN: ${{ inputs.TOKEN }}
        REPO_NAME: ${{ inputs.REPO_NAME }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
      run: |
        echo $ORG_NAME && echo $REPO_NAME &&
        output=$(curl -H "Authorization: token ${TOKEN}" \
        https://api.github.com/repos/$ORG_NAME/$REPO_NAME/pulls\?state\=closed\&sort\=updated\&direction\=desc\&per_page\=1 \
        | jq --raw-output '.[].closed_at') && \
        if [ $(date -u +%s) -gt $(( $(date -d $output -u +%s) + 86400 )) ]; then exit 0; fi
      shell: bash
