name: 'Check merges'
description: 'Check if any merges occurred in the last 24 hours'
inputs:
  GITHUB_API_TOKEN:
    description: 'Github Token'
    required: true
  REPO_NAME:
    description: 'Repository name'
    required: true
  ORG_NAME:
    description: 'Organization name'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Check if there were any merge events in the last 24 hours
      id: check_merges
      env:
        TOKEN: ${{ inputs.GITHUB_API_TOKEN }}
        REPO_NAME: ${{ inputs.REPO_NAME }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
      run: |
        echo $TOKEN && echo $MM &&
        curl -H "Authorization: token ${TOKEN}" \
        https://api.github.com/repos/altooro/$REPO_NAME/pulls\?state\=closed\&sort\=updated\&direction\=desc\&per_page\=1
      shell: bash
